// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBceQAENu0yVcREPzm-aXhBNSgnBkKBWJQ',
    appId: '1:257756841369:web:86c98641967f8715287f08',
    messagingSenderId: '257756841369',
    projectId: 'women-safety-1-d8de2',
    authDomain: 'women-safety-1-d8de2.firebaseapp.com',
    storageBucket: 'women-safety-1-d8de2.appspot.com',
    measurementId: 'G-0EH33ZCQ8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCShDT8u192QDmnN9qNeRAa0VhHplzbBQw',
    appId: '1:257756841369:android:b09c709081730f5a287f08',
    messagingSenderId: '257756841369',
    projectId: 'women-safety-1-d8de2',
    storageBucket: 'women-safety-1-d8de2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU7SijqSq4E8-hiK3uVqmizGsoLOfvgG4',
    appId: '1:257756841369:ios:2e5c0ec6515b434b287f08',
    messagingSenderId: '257756841369',
    projectId: 'women-safety-1-d8de2',
    storageBucket: 'women-safety-1-d8de2.appspot.com',
    iosBundleId: 'com.example.sihWomenSafety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU7SijqSq4E8-hiK3uVqmizGsoLOfvgG4',
    appId: '1:257756841369:ios:2e5c0ec6515b434b287f08',
    messagingSenderId: '257756841369',
    projectId: 'women-safety-1-d8de2',
    storageBucket: 'women-safety-1-d8de2.appspot.com',
    iosBundleId: 'com.example.sihWomenSafety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBceQAENu0yVcREPzm-aXhBNSgnBkKBWJQ',
    appId: '1:257756841369:web:4fe1fc48c7123ba2287f08',
    messagingSenderId: '257756841369',
    projectId: 'women-safety-1-d8de2',
    authDomain: 'women-safety-1-d8de2.firebaseapp.com',
    storageBucket: 'women-safety-1-d8de2.appspot.com',
    measurementId: 'G-9G15ZNNKNK',
  );
}
